### ISSUE TITLE
Indent list bugs

### ISSUE THREAD

**Issue by Zinston** [odoo-dev/jabberwock#107] opened 2020-02-23 23:10 UTC
I tried the indentation of lists a little bit and they need work... Hopefully all the problems I saw had the same source, that's possible. 
Take for instance our jabberwockipedia example and try to outdent
"5.1 History
5.2 Sample translations".

**Comment by dmo-odoo** [comment] 2020-02-24 07:03
Aren't you supposed to be on holidays ? I could not reproduce the issue, though. Well, to be fair, I could, the very first time. Then all further attempts worked as expected. There might be a catch however. If you start selecting from the white space at the right of "5. Translations", the `range.start` marker will be *inside* "5. Translations" so it will be the startContainer, even though you can't see it visually, and it gets outdented as well. I'm not sure this is a bug of indent though, that might be something we want to tweak in the normalizer since it's not great to have a selection that does not visually match with what is displayed on screen.

**Comment by Zinston** [comment] 2020-02-24 09:27
I _am_ indeed supposed to be on holiday ^^' We're leaving in a couple of hours. I was just curious since you merged things this weekend (weren't you supposed to be on weekend ? ^^') and then when I tried I saw that and thought I'd better report it.
Now i tried again and for some reason everything is fine. I don't get it because I didn't change anything and I swear yesterday evening it didn't work well. Everything underneath my selection was unlisted.

**Comment by Zinston** [comment] 2020-02-24 09:29
Now I just got the bug like 5x in a row again, then it disappeared again!

**Comment by Zinston** [comment] 2020-02-24 09:37
Ok found it! It's the stupid normalizer bug acting up!
Click within 5.1 His[]tory, then holding shift click somewhere in the row below, then quickly shift-tab.
The thing is since it takes a while for the badly normalized selection to show up it's possible to shift-tab _before_ you see the real new selection. In any case then the selection is at "5.2 [Sample translation]". Weirdly then if I shift-tab, everything below gets outdented too. But if I make the exact same selection manually without the bug I don't have the issue

**Comment by dmo-odoo** [comment] 2020-03-16 13:55
I'm closing this as we merged the new Normalizer.

**Closed by dmo-odoo** 2020-03-16 13:55 UTC
Labels: bug
